version: '3.8'
services:
  templatetbot:
    image: templatetbot
    build:
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_WEBHOOK_DOMAIN=${BOT_WEBHOOK_DOMAIN}
      - BOT_WEBHOOK_PATH=${BOT_WEBHOOK_PATH}
      - BOT_LOCALHOST=${BOT_LOCALHOST}
    expose:
      - 8443
    ports:
      - "8443:8443"